config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: 'home#index'

  get '/' => 'home#index', as: 'home'

  get '/categories' => 'categories#index', as: 'categories'
  get '/categories/new' => 'categories#new', as: 'new_category'
  post '/categories' => 'categories#create', as: 'create_category'
  get '/categories/:id' => 'categories#show', as: 'category'
  get '/categories/:id/edit' => 'categories#edit', as: 'edit_category'
  patch '/categories/:id' => 'categories#update', as: 'update_category'
  delete '/categories/:id' => 'categories#destroy', as: 'delete_category'  

  get '/categories/:category_id/tasks(.:format)' => 'tasks#index', as: 'category_tasks'
  get '/categories/:category_id/tasks(.:format)/new' => 'tasks#new', as: 'new_category_task'
  post '/categories/:category_id/tasks(.:format)' => 'tasks#create', as: 'create_category_task'
  get '/categories/:category_id/tasks/:id(.:format)' => 'tasks#show', as: 'category_task' 
  get '/categories/:category_id/tasks/:id/edit(.:format)' => 'tasks#edit', as: 'edit_category_task'
  patch '/categories/:category_id/tasks/:id' => 'tasks#update', as: 'update_category_task'
  delete '/categories/:category_id/tasks/:id' => 'tasks#destroy', as: 'delete_category_task'

  resources :users do
    resources :categories do
      resources :tasks 
    end
  end
end

  # get '/users/sign_out' => 

  # 'user'
  # 'user/:id'
  # 'user/:new'
  # 'user/edit'

  # delete '/users/sign_out(.:format)' => 'users/sessions#destroy', as: 'destroy_user_session'
  # get '/resource/sign_up' => 'registrations#new', as: 'registration'

app/models/task.rb
class Task < ApplicationRecord
    validates :name, :details, :deadline, presence: true
    belongs_to :category
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_action :set_task, only: %i[show edit update destroy] 

    def index
        @category = Category.find params[:category_id]
        @tasks = Task.all
    end

    def new
        @task = Task.new
        @category = Category.find params[:category_id]
    end

    def create
        @category = Category.find params[:category_id]
        @task = @category.tasks.new(task_params)
        
        respond_to do |format|
            if @task.save
                format.html { redirect_to category_task_url(@category, @task), notice: "Task was successfully created." }
                format.json { render :show, status: :created, location: @task }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def show
    end
    
    def edit
    end

    def update
        respond_to do |format|
            if @task.update(task_params)
              format.html { redirect_to category_task_url(@category, @task), notice: "Task was successfully updated." }
              format.json { render :show, status: :ok, location: @task }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @task.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @task.destroy

        respond_to do |format|
            format.html { redirect_to category_tasks_url, notice: "Task was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private

    def set_task
        @category = Category.find(params[:category_id])
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:name, :details, :deadline)
    end
    
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: [@category, task]) do |form| %>
    <% if task.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
  
        <ul class='form-errors'>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, maxlength: 30, autocomplete: 'off'  %>
    </div>
  
    <div>
      <%= form.label :details, style: "display: block" %>
      <%= form.text_area :details, maxlength: 335, rows: 6, autocomplete: 'off' %>
    </div>

    <div>
      <%= form.label :deadline, style: "display: block" %>
      <%= form.date_field :deadline %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/tasks/_nav.html.erb
<nav>
    <%= link_to "Home", home_path %>
    <%= link_to "Journal", categories_path %>
    <%= image_tag "nav-logo.png", class: 'nav-logo'%>       
    <span>FAQ</span>
    <span>Contact</span>
</nav>

app/views/tasks/_task.html.erb
<div class='task-wrapper'>
<div id="<%= dom_id task %>" class='task'>
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>
  <p>
    <strong>Deadline:</strong>
    <%= task.deadline %>
  </p>
  <p>
    <strong>Details:</strong>
    <%= task.details %>
  </p>
</div>
</div>

app/views/tasks/edit.html.erb
<section>
<%= render "nav" %>
<div class='task'>
<h1 class='title'>Edit Task</h1>
<div class='form-container'>
<%= render "form", task: @task %>
</div>

</div>
</section>

app/views/tasks/index.html.erb
<%= render "nav" %>
<h1 class='title'><%= @category.name %></h1>
<h1 class='title'>Tasks</h1>

<div id="tasks">
<div id='task-container'>
  <% @category.tasks.each do |task| %>
    <%= link_to render(task), category_task_path(@category, task) %>
  <% end %>
  <div id='new-task-container'>
    <%= link_to "+", new_category_task_path %>
  </div>
</div>
</div>

app/views/tasks/new.html.erb
<section class='new-task-section'>
<%= render "nav" %>
<div class='new-container'>
<h1 class='title'>New Task</h1>
<div class='form-container'>
<%= render "form", task: @task, category: @category %>
</div>

<div class='new-back-container'>
  <%= link_to "Back to tasks", category_tasks_path, class: 'edit-link' %>
</div>
</div>
</section>

app/views/tasks/show.html.erb
<%= render "nav" %>
<section>
<div class='show-container'>
<%= render @task %>

<div class='show-edit-container'>
  <%= link_to "Edit Task", edit_category_task_path(@category, @task), class:'edit-link' %>
  <%= button_to "Destroy Task", delete_category_task_path(@task), method: :delete, class: 'delete-button' %>
  <%= link_to "Back to tasks", category_tasks_path, class:'edit-link' %>
</div>
</div>
</section>