config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: 'home#index'

  get '/' => 'home#index', as: 'home'

  get '/categories' => 'categories#index', as: 'categories'
  get '/categories/new' => 'categories#new', as: 'new_category'
  post '/categories' => 'categories#create', as: 'create_category'
  get '/categories/:id' => 'categories#show', as: 'category'
  get '/categories/:id/edit' => 'categories#edit', as: 'edit_category'
  patch '/categories/:id' => 'categories#update', as: 'update_category'
  delete '/categories/:id' => 'categories#destroy', as: 'delete_category'  

  get '/categories/:category_id/tasks(.:format)' => 'tasks#index', as: 'category_tasks'
  get '/categories/:category_id/tasks(.:format)/new' => 'tasks#new', as: 'new_category_task'
  post '/categories/:category_id/tasks(.:format)' => 'tasks#create', as: 'create_category_task'
  get '/categories/:category_id/tasks/:id(.:format)' => 'tasks#show', as: 'category_task' 
  get '/categories/:category_id/tasks/:id/edit(.:format)' => 'tasks#edit', as: 'edit_category_task'
  patch '/categories/:category_id/tasks/:id' => 'tasks#update', as: 'update_category_task'
  delete '/categories/:category_id/tasks/:id' => 'tasks#destroy', as: 'delete_category_task'

  resources :users do
    resources :categories do
      resources :tasks 
    end
  end
end

  # get '/users/sign_out' => 

  # 'user'
  # 'user/:id'
  # 'user/:new'
  # 'user/edit'

  # delete '/users/sign_out(.:format)' => 'users/sessions#destroy', as: 'destroy_user_session'
  # get '/resource/sign_up' => 'registrations#new', as: 'registration'

app/models/category.rb
class Category < ApplicationRecord
    validates :name, :details, presence: true
    has_many :tasks
    belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: %i[show edit update destroy] 

    def index
        @user = current_user 
        # params[:user_id]
        @categories = Category.all
    end

    def new
        @user = current_user
        #params[:user_id]
        @category = Category.new
    end

    def create
        @user = current_user
        # @user = User.find params[:user_id]
        @category = @user.categories.new(category_params)
        # @category = Category.new(category_params)

        respond_to do |format|
            if @category.save
                format.html { redirect_to user_category_url(@user, @category), notice: "Category was successfully created." }
                # format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
                format.json { render :show, status: :created, location: @category }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @category.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def show
    end
    
    def edit
    end

    def update
        respond_to do |format|
            if @category.update(category_params)
              format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
              format.json { render :show, status: :ok, location: @category }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @category.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @category.destroy

        respond_to do |format|
            format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private 
    
    def set_category
        @user = current_user
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name, :details)
    end
    
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_category.html.erb
<div class='category-wrapper'>
<div id="<%= dom_id category %>" class='category'>
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>
  <p>
    <strong>Details:</strong>
    <%= category.details %>
  </p>
</div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: [@user, @category]) do |form| %>
    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
  
        <ul class='form-errors'>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, maxlength: 30, autocomplete: 'off'  %>
    </div>
  
    <div>
      <%= form.label :details, style: "display: block" %>
      <%= form.text_area :details, maxlength: 335, rows: 6, autocomplete: 'off' %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/categories/_nav.html.erb
<nav>
    <%= link_to "Home", home_path %>
    <%= link_to "Journal", categories_path %>
    <%= image_tag "nav-logo.png", class: 'nav-logo'%>     
    <span>FAQ</span>
    <span>Contact</span>
</nav>

app/views/categories/edit.html.erb
<section>
<%= render "nav" %>
<div class='edit-container'>
<h1 class='title'>Edit Category</h1>
<div class='form-container'>
<%= render "form", category: @category %>

</div>
</div>
</section>

app/views/categories/index.html.erb
<%= render "nav" %>
<h1 class='title'>Categories</h1>

<div id="categories">
<div id='category-container'>
  <% @user.categories.each do |category| %>
    <%= link_to render(category), category %>
  <% end %>
  <div id='new-category-container'>
    <%= link_to "+", new_category_path %>
  </div>
</div>
</div>

app/views/categories/new.html.erb
<section class='new-section'>
<%= render "nav" %>
<div class='new-container'>
<h1 class='title'>New Category</h1>
<div class='form-container'>
<%= render "form", category: @category %>
</div>
</div>
</section>

app/views/categories/show.html.erb
<%= render "nav" %>
<section>
<div class='show-container'>
<%= render @category %>

<div class='show-edit-container'>
  <%= link_to "Edit Category", edit_category_path(@category), class: 'edit-link' %>
  <%= button_to "Destroy Category", @category, method: :delete, class: 'delete-button' %>
  <%= link_to "Show Tasks", category_tasks_path(@category), class: 'edit-link' %>
</div>

</div>
</section>